### PR TITLE
Add ipv6 support

### PR DESCRIPTION
**Pull request by evertramos**

### CODE REVIEW

**Comment by evertramos** [comment]
Thank you very much @j7an I will test it again. I could not get it running! But will figure it out.

**Comment by j7an** [comment]
@evertramos Did nginx-gen start? I've noticed some times it doesn't start. Since then I've added `depends_on` docker-compose statement for letsencrypt and nginx-web where letsencrypt depends on nginx-gen and nginx-web depends on nginx-gen and letsencrypt

**Comment by moritz89** [comment]
Is this change really needed? Just tested it, and docker binds to both ipv4 and ipv6 ports when specified. Tried on separate docker compose project with following spec:

    grafana:
      image: grafana/grafana:4.6.3
      container_name: grafana
      ports:
        - "3000:3000"

**Comment by j7an** [comment]
@moritz89 IPv6 is not supported in Docker Compose 3 yet. See details here https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/45

**Comment by moritz89** [comment]
Jupp, after a bit of research, the 3 series of the docker compose spec [does not support IPv6](https://docs.docker.com/compose/compose-file/#enable_ipv6) yet. So I guess, wait until that happens or switch to the 2 series...

**Pull request closed without merging**
