### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mariuccio90**
if putting my external ip the proxy brakes.

### CODE REVIEW

**Comment by evertramos** [comment]
In fact you should use your interface for the external access...

**Comment by evertramos** [comment]
In fact you should add your ip address used by your internet interface... so I have updated it.

**Comment by mariuccio90** [comment]
The issue is that , if i put my external (public ip) nothing works, but if i leave 0.0.0.0 everything is fine

**Comment by evertramos** [comment]
You are using the wrong ip addres...

Check your interfaces and use the correct ip. If you are using AWS you will have a private ip address from your interface used to connect from the outside.

**Pull request closed without merging**
