### PR TITLE
IPv6 NAT

### PR DESCRIPTION
**Pull request by j7an**
Add IPv6 NAT functionality

- Add IPv6 variable in .env.sample to map external IPv6 address
- Map IPv6 port forwarding in Docker compose files
- Add ENABLE_IPV6 to compose files to enable IPv6 routing from host
- Add ipv6nat in start.sh to enable IPv6 NAT between containers
- Update docker network create in start.sh to assign IPv6 addresses to all containers
- Resolves issue [IPv6 Configuration](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/45#issuecomment-424880799)

### CODE REVIEW

**Comment by j7an** [comment]
Ran multiple tests on two different VMs. Port 80 and 443 are forwarding correctly. So there's no need to investigate port issue.

To test I setup a `whoami` container with domain name running following command to test routing:

IPv4:
`curl -4 http://MY_DOMAIN.COM`
Result:
```
Hostname: 47d7b7ce250d
IP: 127.0.0.1
IP: ::1
IP: 172.19.0.5
IP: fd00:dead:beef::5
IP: fe80::42:acff:fe13:5
GET / HTTP/1.1
Host: MY_DOMAIN.COM
User-Agent: curl/7.54.0
Accept: */*
Connection: close
X-Forwarded-For: XX.XXX.XXX.XX
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Ssl: off
X-Real-Ip: XX.XXX.XXX.XX
```

IPv6:
`curl -6 http://MY_DOMAIN.COM`
Result:
```
Hostname: 47d7b7ce250d
IP: 127.0.0.1
IP: ::1
IP: 172.19.0.5
IP: fd00:dead:beef::5
IP: fe80::42:acff:fe13:5
GET / HTTP/1.1
Host: MY_DOMAIN.COM
User-Agent: curl/7.54.0
Accept: */*
Connection: close
X-Forwarded-For: XXXX:XXXX:XXXX:XXX:XXXX:XXX:XXXX:XXXX
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Ssl: off
X-Real-Ip: XXXX:XXXX:XXXX:XXX:XXXX:XXX:XXXX:XXXX
```

whoami `docker-compose.yml`

```
version: '3'

services:
    whoami:
        container_name: whoami
        image: emilevauge/whoami
        environment:
            VIRTUAL_HOST: MY_DOMAIN.COM

networks:
    default:
       external:
         name: webproxy
```

**Comment by evertramos** [comment]
I could not really test it... but added you as collaborator on this repo. Please always use pull requests to this repo using ipv6 branch and for master I myself would like to review the PR before merging, ok? Thanks!

**Comment by j7an** [comment]
@evertramos I can add a test directory with `whoami` test container files as well as a `readme.md` in the directory detailing the steps to test this branch.

Do you think it would be a good idea to create a new issue for IPv6 testing to ask anyone interested to help test this branch and post their results in the issue?

**Comment by evertramos** [comment]
I think it would be good!

**Comment by samip5** [comment]
Why are you doing IPv6 NAT? I would love to disable that functionality.

**Comment by samip5** [comment]
> Why are you doing IPv6 NAT? I would love to disable that functionality.

And set it to use specific range.

**Comment by j7an** [comment]
> Why are you doing IPv6 NAT? I would love to disable that functionality.

@samip5 IPv6 is not currently in the master branch so you don't have to worry about disabling it.

The main reason for IPv6 is to help troubleshoot and log real IPs instead of Docker internal IPv6 addresses if the visitor used IPv6 to access the web application. IPv6 requires DNS configuration and IPv6 address assigned to the VPS. Since most VPS do not enable IPv6 by default, having IPv6 NAT in the code would not change the default behavior at all.

**Comment by samip5** [comment]
I'm aware that it's not in the master branch, but if my server has a IPv6
prefix in daemon.json set, it should be used in the stack too and not IPv6
NAT.

The NAT functionality itself on the IPv6 branch should have a way to enable
it and disable.

**Comment by j7an** [comment]
By default the Docker stack only has NAT enabled for IPv4. This is why the real IPv4 addresses can be passed from Nginx to any application containers without any modification. Docker Compose does not support IPv6 the last time I checked. Even if it does support IPv6, we still need a NAT which Docker needs to implement natively. In the mean time we'll have to settle for `robbertkl/ipv6nat` Docker image to accomplish the IPv6 NAT.

@evertramos To disable forwarding of IPv6 addresses on this branch we just need to comment out the following lines in the `.env` and `docker-compose.yml` file, correct?

.env
```
IPv6=::1
```

docker-compose.yml
```
- "${IPv6:-::/0}:80:80"
- "${IPv6:-::/0}:443:443"
```

@samip5 This branch is still a work in progress. When I have time I'll merge in the latest changes from master as well as update the start.sh script for better security. If you have time to help test when this is done, that would be great.

**Comment by evertramos** [comment]
@j7an 

Correct!

**Comment by evertramos** [comment]
Hello @j7an !

May I delete the ipv6 branch? Or you might use it some how?

I also would like to know if you could test it the new version v0.5 with ipv6.

Thanks!

**Comment by j7an** [comment]
Hi Evert. Go ahead. It’s been a while since I last touched your repo. I’m sure you’ve made some amazing improvements since that branch was updated. 

Sure. I’ll check out the new ipv6 implementation. Thanks for the merge.

**Pull request merged**
